### ISSUE TITLE
ILSVRC2012 Dataset

### ISSUE THREAD

**Issue by kanzaali** [Hey1Li/Salient-Relevance-Propagation#1]
Hi, 

I want to run your code for research purpose but I am unable to download the dataset. The website is not allowing me to download anything. 
Any alternate?

**Comment by Hey1Li** [comment]
Hi,

I am glad to hear that you are interested in my work.
However, I have no control over whom ImageNet allows downloading the
dataset. That being said, the dataset should be free to download for
research purpose. You need to register an account and should be able to
download original images after verification. Hope this can help.

Best wishes,

-----------------------------------------------------------------
Heyi Li
Ph.D. Candidate, Computer Science Department
Visual Analytics and Imaging Lab
Stony Brook University, SUNY
-----------------------------------------------------------------

**Comment by kanzaali** [comment]
OK thank you so much.
